from __future__ import annotations

from typing import Protocol


class BrowserAdapter(Protocol):
    def goto(self, url: str) -> None: ...

    def wait_visible(self, selector: str, timeout_ms: int = 0) -> None: ...

    def click(self, selector: str) -> None: ...

    def fill(self, selector: str, value: str) -> None: ...

    def text_snapshot(self) -> str: ...

    def screenshot(self, name: str) -> str: ...
